### ISSUE TITLE
Crash when using set("genWeight")

### ISSUE THREAD

**Issue by Kaelten** [superckl/BiomeTweaker#11]
Was just testing out the genWeight commands with this script.

    allBiomes = forAllBiomes()
    allBiomes.set("genWeight", 1)

    plains = forBiomesOfTypes("PLAINS")
    plains.set("genWeight", 50)

Crash report here: https://gist.github.com/Kaelten/4b482c74ed3faf253b5e

**Comment by superckl** [comment]
How dare you divide by 0! This is happening because you've set all the weights to 1. When Minecraft attempts to grab a random integer, it divides an integer < 10 by 10, which results in 0. A modulus is then calculated with that value, throwing the error.

A fix for this will require telling the [TrackedLists](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/BiomeManager.java#L201) that they are modded, so the division does not occur. Since this class is private, some fairly heavy reflection will need to be done to access the arrays and classes. Something [similar to this](https://github.com/superckl/BiomeTweaker/blob/master/src/main/java/me/superckl/biometweaker/util/BiomeHelper.java#L305) has already been done for BiomeDictionary types though.

A temporary fix is to increase the genWeight until the crash no longer occurs. I'll have a fix ready by tomorrow evening.

**Comment by superckl** [comment]
A build with a fix is now available on my Jenkins server. I've only tested it a bit:

http://jenkins.superckl.me/job/BiomeTweaker/65/

**Comment by Kaelten** [comment]
Awesome.  I'll test it out as soon as I can, I've got to crash right now.  Thanks for the quick turn around! :)

**Comment by Kaelten** [comment]
New build works great it seems.  Also do I need to reload the game to make sure the new script is loaded or just gen a new world?

**Comment by Kaelten** [comment]
actually on further inspection it seems like sub ten weights may be favored incorrectly :/

**Comment by superckl** [comment]
If you edited the scripts, you can reload them either through the Forge config gui or through the in-game command. You'll have to do one of these for the changes to take effect.

Generation weights is a bit hard to test, but I'll try to find some time to setup some tests.

**Comment by superckl** [comment]
My tests have been inconclusive, and I have not seen any other reports of this. If you can provide me some examples, I'll look into it more. for now I'm going to close this issue.
