### ISSUE TITLE
Tweaks not appearing in game despite being present in the output

### ISSUE THREAD

**Issue by Ironmango21** [superckl/BiomeTweaker#130]
I have written a script to make some tweaks to vanilla biomes, but some changes are not appearing when I generate a new world.  Everything works except for the lines that disable snow in extreme hills, replace magma blocks with netherack, and add custom flower patches. The paste of my script is here:

https://pastebin.com/awKLde9q

At first I thought this was an issue with the script and placement stages, but in the biome outputs all extreme hills biomes state that snow is disabled. Despite this, nothing is changed in game. The mob spawns and feature removal seem to be working fine, these items seem to be the only issue. I am running the latest version of BiomeTweaker and have no other world generation mods present. Any assistance would be appreciated, thanks in advance!

**Comment by superckl** [comment]
I'm going to need a full log file to help you with this. I can't tell if it's your script or BiomeTweaker that's messing up otherwise.

**Comment by Ironmango21** [comment]
Oh, I'm sorry. Here it is: https://pastebin.com/jiK06a2j It looks like it doesn't recognize the newClusterDecoration lines so maybe I've done something wrong? But it makes no mention of the snow being persistent in extreme hills or the magma blocks not being replaced, so I'm not really sure.

**Comment by superckl** [comment]
My my, you've managed to find a bunch of niche use cases. A few things:

1. It's `newClusterDecoration()`, not `newCluserDecoration`.
2. `removeOre` was added very recently (v 3.1). The version you're running doesn't have it. You can go grab the latest version on the CurseForge page.
3. Chunk population is a bit strange in the nether. It follows a different pattern:

    BIOME_BLOCKS -> PRE_POPULATE -> POST_POPULATE -> PRE_DECORATE -> POST_DECORATE

Magma is placed during decoration, so the only stage you can use is "POST_DECORATE".

4. It looks like they've messed up the rain/snow logic in an update since I've added that feature. It will snow if it can rain **or** snow **and** the temperature is below 0.15. Try setting the temperature to 1 or something higher in hills to disable snow.

**Comment by Ironmango21** [comment]
Thank you! That solves most of my problems. I've adjusted my script and it seems that everything is working fine except the magma block replacement, which continues to be stubborn. When I go into my logs it seems I receive this message every time I load a chunk: 

[Server thread/DEBUG] [FML/]: Minecraft loaded a new chunk (-10, -6  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

So I assume biometweaker is at least attempting to edit something. The full log is here: 

https://pastebin.com/7ffnsAGh

Also, this might be a simple mistake on my part again, but I can't seem to get GRASSperChunk to work. Here is my updated script:

https://pastebin.com/G2hv9hCV

Thank you once again for your help! It is greatly appreciated.
