### ISSUE TITLE
The name galacticraftplanets:mars flat has been registered twice

### ISSUE THREAD

**Issue by donqixot** [superckl/BiomeTweaker#144]
I am using MC 1.11.2, forge 13.20.1.2530, BiomeTweaker-1.11.2-3.1.304, BiomeTweakerCore-1.11.2-1.0.18, GalacticraftCore-1.11.2-4.0.0.118, Galacticraft-Planets-1.11.2-4.0.0.118.

I have one line command in my script:
Tweaker.createBiome("MarsPlus", "galacticraftplanets:mars flat")

Here is the log after reloading this script.
https://pastebin.com/AYpz5rkf

What interesting is this snippet:
"The name galacticraftplanets:mars flat has been registered twice, for micdoodle8.mods.galacticraft.planets.mars.world.gen.BiomeGenFlatMars@71092212 and micdoodle8.mods.galacticraft.planets.mars.world.gen.BiomeGenFlatMars@191e77b3."

Does it mean Galacticraft biomes cannot be "copied" over?

**Comment by superckl** [comment]
Yep, any GC biome cannot be copied since they register themselves in their constructors rather than at a fixed point in startup.

https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/java/micdoodle8/mods/galacticraft/planets/mars/world/gen/BiomeGenFlatMars.java#L13

This would have to be fixed on their side. @radfast

**Comment by donqixot** [comment]
Ok, thanks.
