### ISSUE TITLE
addToGeneration() error "No enum constant net.minecraftforge.common.BiomeManager.BiomeType.SANDY"

### ISSUE THREAD

**Issue by donqixot** [superckl/BiomeTweaker#146]
I am using MC 1.11.2, forge 13.20.1.2530, BiomeTweaker-1.11.2-3.1.304, BiomeTweakerCore-1.11.2-1.0.18, GalacticraftCore-1.11.2-4.0.0.118, Galacticraft-Planets-1.11.2-4.0.0.118.

I am trying to use function addToGeneration(), which requires biome dictionary type. According to wiki for function forBiomesOfTypes():
"You can find the possible entries in the description for the removeDicType command. You'll have to look in the output files to see a biome's dictionary types. "

I did not find anything under removeDicType(), but I found following types in some output files: "DEAD","DRY","COLD","SANDY"

So I tried this script:

Tweaker.createBiome("MarsPlus")
mars = forBiomes("biometweaker:MarsPlus")
mars.set("name", "Mars Plus")
mars.addToGeneration("SANDY", 25)

That gives me error:
java.lang.IllegalArgumentException: No enum constant net.minecraftforge.common.BiomeManager.BiomeType.SANDY

Anything I am doing wrong?

**Comment by superckl** [comment]
The addToGeneration documentation tells you to "See the create command for the possible values." which you won't find helpful because there aren't any listed... I'll have to fix that too. The possible values are given here:

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeManager.java#L180

**Comment by donqixot** [comment]
Ok, thanks, closing.
