### ISSUE TITLE
Not really an "issue"

### ISSUE THREAD

**Issue by C0LiSii0N** [superckl/BiomeTweaker#186]
Ok so I continued to modify my stuff and I find out that:

When we inherit stuff from other biome with `inheritProperties` we have to put everything in lower case otherwise the mod detect them like non-existing.

We can't put multiple properties at once as said in the wiki, need one line per properties.

`contiguousReplacement`, `liquidFillerBlock` and `genInitialSnow` doesn't exist.

`genWeight` and `genScatteredFeatures` can't be inherited.

When we put OCEAN in `addDicTypes` it put WATER at the same time(Also would be great to explain a bit what each type does, at the moment there's no way to know)

**Comment by C0LiSii0N** [comment]
I was trying stuff and I think you should dig on the generator option `fixedBiome` maybe a way to remove hardcoded biomes.

**Comment by superckl** [comment]
If this isn't an issue, why are you posting it here?

You should be able to specify multiple properties when inheriting properties. Please post your code and the errors you saw.

contiguousReplacement was just removed in the recent dev builds. The wiki hasn't been updated to reflect that yet because it isn't released. genInitialSnow requires BTCore. liquidFillerBlock doesn't exist anymore.

Dictionary Types don't "do" anything. They're just a way to say what a biome is. "Ocean" means the biome is an oceanic biome. "Dry" means it's dry. That changes nothing about the actual biome.

**Comment by C0LiSii0N** [comment]
> If this isn't an issue, why are you posting it here?

I posted here bc I don't know where else to post this. I thougt that you would know that some things are different from what you posted in the wiki, you know, to avoid some issue that can be solved just by puting some extra lines in the wiki(like for the need of putting everything in lower case for inherit)

> You should be able to specify multiple properties when inheriting properties. Please post your code and the errors you saw.

When I try to copy a biome with second argument;
config: https://pastebin.com/7eCjYjdm
logs: https://pastebin.com/t9N7XAqs
crash-report: https://pastebin.com/65YRq5w6

When I inherit ALL properties showed in the wiki under SET separately(With capitals letters);
config: https://pastebin.com/FWKfuaRp
logs: https://pastebin.com/82Cqj4h0
see lines 47-65 + 87

When I inherit ALL properties showed in the wiki under SET separately(all in lower case);
config: https://pastebin.com/PLENCYfM
logs: https://pastebin.com/ypay5S6W
see lines 47-49

When I inherit ALL properties showed in the wiki under SET at the same time(all in lower case);
config: https://pastebin.com/mNWGtGDt
logs: https://pastebin.com/M1WASCGd
see line 41

> contiguousReplacement was just removed in the recent dev builds. The wiki hasn't been updated to reflect that yet because it isn't released. liquidFillerBlock doesn't exist anymore.

I use the latest build posted on curseforge, not a dev build

> genInitialSnow requires BTCore.

I have BTCore, there's my config: https://pastebin.com/DfT30W73

**Comment by superckl** [comment]
There is a link to the discord channel on the wiki for talking about non-issues.

I'll look at the rest of this soon, but I can tell you right now that the properties you can't copy aren't copyable by design. You also have the Gen initial snow feature disabled in your BTCore config, which is why it isn't working.

**Comment by C0LiSii0N** [comment]
Ho well, my bad didn't saved my core cofig --' I'll let the issue open until you check/fix the others "problems" :)
