### ISSUE TITLE
/btoutput command not reporting correctly

### ISSUE THREAD

**Issue by Graagh** [superckl/BiomeTweaker#190]
Using the Conquest Reforged launcher version of 1.12.2.  That adds new biomes and world generation, so it's possible the error is related to that rather than BiomeTweaker.

Using BiomeTweaker-1.12.2-3.2.345 and  BiomeTweakerCore-1.12.2-1.0.39, the initial output files for the individual biomes shows correct spawn tables, but when I issue the command /btoutput in-game the regenerated output files show all the spawn tables empty, when there are obviously mobs generating in the game.  This is in a Conquest-Reforged-specific world type.  I will check to see if this happens in vanilla world types.

The biome manager table is also empty for vanilla biomes, but that is also empty in the initial output files, so I suspect that is not the same issue but is Conquest removing the vanilla biomes from generation in order to substitute its own replacements.

Edit: Sorry, you might also need this - forge-1.12.2-14.23.3.2669

**Comment by superckl** [comment]
I believe this is all due to Conquest Reforged. The initial output generation and the output command use the same method. There is no difference between the code they use to generate the output files. Conquest Reforged is most likely removing all the spawns at some point after the initial output generation.

If you want to verify this, try the command without conquest reforged installed.

**Comment by Graagh** [comment]
I suspected this could be the problem.  I was in the process of setting up a 1.12.2 vanilla install to test it since I haven't played vanilla in forever :-), but I'll take your word for it on this one.  The new Conquest Reforged is more than a little screwy in several ways...
