### ISSUE TITLE
Meta Data not Working for Setting Top Block

### ISSUE THREAD

**Issue by Pillowkeeper** [superckl/BiomeTweaker#2]
Hello,

I was trying to replace all of the grass in a plains biome with light blue wool (35:3), but the world does not generate and leads me back to the main page. Do the parameters not work with block IDs or meta data, and I need to use minecraft:wool, or is there an issue.

Thank you for your time,
Pillowkeeper

**Comment by superckl** [comment]
Block IDs aren't a thing in 1.7+, so I'm not sure where you getting that. You do need to use "minecraft:wool". I'm sure if there is a way to get metadata in there currently. I'll have to look into it. I'll get back to you later on that.

**Comment by Pillowkeeper** [comment]
Ok thanks for the quick response.

**Comment by superckl** [comment]
There is no way to add metadata with the way MC currently generates. Doing so would require a fairly extensive overhaul, which would break a lot of other generation mods. You're stuck with white wool using "minecraft:wool".

**Comment by keybounce** [comment]
AARGGGG.

I actually NEEDED Podzol as a top block.
... I can, of course, use dirt, but then I can't tell top block dirt from underground dirt ... and "grass" has problems in that it will spread.

The issue is that I need to let COG do some major customizations, and for the stuff generating in this pack, COG needs deferred of 32. Which means chunks will exist, and do things (grass spread, etc) for a while before COG can erase grass if it exists.

I've already seen grass spread down to 59, and that was without even trying. It could go deeper.

... I can eliminate all grass from Y=1 to Y=255. But I want to be able to target a block replacement for topblocks, while still letting trees be placed in the ground during worldgen. (They'll be killed before the player arrives, but they need to exist / be placed.)

Sigh. OK, back to Grass, and ... just treat any cave-spreading grass as a top block.

**Comment by keybounce** [comment]
Ohh, Gany's surface, 1.10.0, has coarse dirt, and it lets trees grow.

So I can make this work ...
