### ISSUE TITLE
Command "removeBOP" doesn't work

### ISSUE THREAD

**Issue by WarriorsCode1** [superckl/BiomeTweaker#221]
I want to remove the vanilla Biome "swampland" from generation. I use the BOP worldgenerator and it doesn't work. If I use the normal worldgenerator and the command "remove()" it works correctly...
my script: 

swampland = forBiomes(6)
swampland.removeBOP()

Am I doing something wrong or is it a bug...? 
If i replace the biome it works with the BOP worldgenerator.

Forge verison: 1.12.2-forge1.12.2-14.23.5.2768
BT version: 1.12.2-3.2.354
BOP version: 1.12.2-7.0.1.2424

**Comment by DWX12** [comment]
I believe that the removeBOP command only targets Biome O Plenty's biomes rather than all biomes. However, if you wanted to disable BoP biomes from showing up, I would suggest going through the BoP configs and disabling them through there. As for vanilla biomes, go through the BiomeTweaker wiki and read about the hard coded biomes. If you want to remove those, you instead have to replace them with a different biome.

**Comment by superckl** [comment]
Seems you resolved this yourself. You should always go through the respective mod's config first. BiomeTweaker can be used if the config options are not present.
