### ISSUE TITLE
Crash with Ye Gamol Chattels

### ISSUE THREAD

**Issue by Qohelethh** [superckl/BiomeTweaker#25]
Ivorforce said to send this to you to see if you can address it. I get the following crash on a server when both Ye Gamol Chattels and BiomeTweaker are installed: https://gist.github.com/Qohelethh/0778f6de115231802753

https://github.com/Ivorforce/YeGamolChattels/issues/8

**Comment by superckl** [comment]
The crash actually results from him [loading the model classes on the server](https://github.com/Ivorforce/YeGamolChattels/blob/master/src/main/java/ivorius/yegamolchattels/blocks/EnumPedestalEntry.java#L13). He never actually does anything with them which is why his mod doesn't crash outright. I first encountered this issue with QuiverBows.

BiomeTweaker attempts to resolve super classes so that it can patch any classes that improperly overrides color methods in BiomeGenBase. When it does this, it fails to resolve the model classes since they simply aren't there. Luckily, there is a way to fix this on my end until @IvorForce manages to get the models classes to not load on the server. Either way, you're going to need an unreleased version of BiomeTweaker, [build 101](http://jenkins.superckl.me/job/BiomeTweaker/101/) or later. I would recommend downloading the [latest build (107)](http://jenkins.superckl.me/job/BiomeTweaker/107/).

With the latest build, everything should work fine, but you will see some exceptions from BiomeTweaker. If those are really annoying you, you can do two things.

1. Enable light asm mode. This will cause BiomeTweaker to not do **any** superclass resolution. This will break color overrides in some biomes, but the errors will disappear.
2. Add the classes to the ASM blacklist. BiomeTweaker will ignore only those classes when resolving superclasses. This is the best solution, but you need to be able to find what classes are causing the crash.

Again, you don't have to do either of these. The latest build will work regardless. These will just remove the errors. I will close this issue when I release version 1.0.

**Comment by Qohelethh** [comment]
Thanks for your detailed reply. I'll download the latest version and give
it a try.

**Comment by Ivorforce** [comment]
Hrm, the classes are not annotated with @SideOnly for whatever reason, which is why it slipped by me and I just load them on the server too. I guess I'll make a note to change that on my end, too - the enums are bad design anyway.

**Comment by superckl** [comment]
http://minecraft.curseforge.com/mc-mods/228895-biometweaker/files/2241592
