### ISSUE TITLE
[Feature request] [1.18.2] Change fog thickness

### ISSUE THREAD

**Issue by jamesjimmy88** [superckl/BiomeTweaker#282]
As discussed on Discord, I would like to ask for the addition of a command to change the fog density/thickness.
Now that I think about it, it would be nice to have a couple optional parameters to define the affected minY and maxY levels so that caves are affected differently (assuming it's even possible and something that's simple to implement. I'm more than okay with just being able to change fog thickness).

**Comment by superckl** [comment]
The following have been added to the set command:

* `fogStartModifier` - a float value applied as a multiplicative modifier to the near plane distance for fog rendering. A value less than one will bring the fog closer to the player.
* `fogEndModifier` - a float value applied as a multiplicative modifier to the far plane distance for fog rendering. A value less than one will bring the fog closer to the player.
* `fogShape` - The shape of the rendered fog. Can be either `CYLINDER` or `SPHERE`.

Please verify these commands work and satisfy your use case. You can find a build with these commands on the jenkins server:
http://jenkins.superckl.me/job/BiomeTweaker%201.18/24/

**Comment by superckl** [comment]
With cc7b9fbf4aa767a3ba5af73f85db939ca0e87d59, this has changed slighty. The `fogShape` remains unchanged, but there are now two new commands for the modifiers:

**addNearFogModifier**

Adds a multiplicative modifier to the near-plane distance for fog. Takes three arguments: A float modifier, and two integers specifying the min and max y to apply this modifier for. The integers are optional and will default to all y-values. Modifiers that apply to the same y-levels will stack multiplicatively.

Example:

```
plains.addNearFogModifier(0.5, 0, 60)
```

**addFarFogModifier**

Adds a multiplicative modifier to the far-plane distance for fog. Identical to `addNearFogModifier` otherwise.

Example:

```
plains.addFarFogModifier(1.5, 70, 90)
```

You can find the build here:
http://jenkins.superckl.me/job/BiomeTweaker%201.18/25/
