### ISSUE TITLE
replace blocks not working - read more

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#44]
Newest dev version x.x.154
when using topblock and fillblock
your not able to replace those blocks with
"allBiomes.registerGenBlockRep(3, "minecraft:dirt", "minecraft:sandstone", 1)

actually doing some testing this code seems to ONLY work on stone why is that. shouldnt this be used for any block to replace another block?

replace biomes dont work some reason - spawns normal world
Void = forBiomes(0-31,33-39,85,106,129-134,140,149,151,155-158,160-167,192-195)
Void.regiserGenBiomeRep(32) <- mega taiga

is it possible to make simple command for ALL vanilla minecraft biomes instead of having to list them all 1 by 1 lol

if u have steam add me resinate. ive found soo many bugs.

**Comment by superckl** [comment]
1. You can't use block replacements to replace top and filler blocks. Why would you not just use the `set` command?

Read: https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement

2. You misspelled `regiserGenBiomeRep`. That's why it doesn't work.

3. Making a command for all vanilla biomes will break compatibility. So no.

Please stop reporting bugs that don't exist.
