### ISSUE TITLE
setAverageBiomeSize() causing weirdness

### ISSUE THREAD

**Issue by Teibidh** [superckl/BiomeTweaker#46]
> modBiomes = forBiomes(101-108,127-128,135-139,150,152-154,159,168-169,170-174,126,124,50-51,53,55,200-228,237-239,241-243)
> altDimension = forBiomes(8,9,101-108,127-128,135-139,150,152-154,159,168-169,170-174)
> allBiomes = forAllBiomes()
> overworldBiomes = subtractFrom(allBiomes,altDimension)
> overworldModBiomes = subtractFrom(modBiomes,altDimension)
> 
> altDimensionModBiomes = intersectionOf(modBiomes,altDimension)
> altDimensionModBiomes.remove()
> 
> cool = forBiomes(200,210,222,223,226)
> cool.addToGeneration("COOL",10)
> warm = forBiomes(206,207,214,219,220,224,225,239,241,242)
> warm.addToGeneration("WARM",10)
> both = subtractFrom(overworldModBiomes,cool,warm)
> both.addToGeneration("COOL",10)
> both.addToGeneration("WARM",10)
> desert = forBiomes(202,207,214,219,239,242)
> desert.addToGeneration("DESERT",10)
> 
> spawnBiomes = forBiomes(35,21,204,216,220,6,224)
> overworldBiomes.set("isSpawnBiome",false)
> spawnBiomes.set("isSpawnBiome",true)
> 
> villageBiomes = forBiomes(35,220,129,5,226,227,214,32,213,12)
> villageBiomes.set("genVillages",true)
> 
> usefulBiomes = forBiomes(35,220,6,21,2,29,126)
> usefulBiomes.set("genWeight",20)
> prettyBiomes = forBiomes(201,204,242,205,209,240,224,225,219,217,216,241,14,37,239,212,22,140,13,211,210,208)
> prettyBiomes.set("genWeight",30)
> 
> Tweaker.setAverageBiomeSize(15)'

So, everything in this script seems to work as I expect it to (making sure some biomes that shouldn't spawn in the overworld don't, adding some mod biomes to the generator and changing the weights around.) Where I run in to trouble is the last line, Tweaker.setAverageBiomeSize(). If I use this with any integer (or with "default",<integer>) I wind up with an entire world created from a single biome. The documentation on the wiki says the integer is a radius in chunks. I'm not sure exactly what size I want, but it doesn't seem to matter what I put in for a value. If the setting is used in the script, I get a single-biome world.

Let me know what other information might be needed.

**Comment by Teibidh** [comment]
Update: I stand corrected, somewhat. I had said it doesn't matter what the integer is, that's not quite accurate. I used the wiki example of 200 (without specifying the worldgen type of default, large, etc) and low and behold, I had more biomes. I started fiddling with it a bit more and discovered that while 100 does not work (generates only one biome), 128 does work. I then decided to try 126, which still generated only one biome. So, something happens when going over 128 (127 may or may not work, honestly, I'm not that motivated right this second :P) ... maybe a typing issue or something?

**Comment by superckl** [comment]
I guess 200 was a pretty poor example to use...

The number you pass is actually a byte. That means it's maximum value is 127. If you input anything over that, it gets truncated to 0.

I can't run your script, since I don't have the mods you do. However, I ran some tests and saw the following:

Biome size 2:
![2015-10-29_13 18 31](https://cloud.githubusercontent.com/assets/2230216/10828061/5989e5be-7e40-11e5-9ca9-e2bbd193aae3.png)

Biome size 4:
![2015-10-29_13 19 32](https://cloud.githubusercontent.com/assets/2230216/10828068/6281b9ee-7e40-11e5-8fd3-81143b4b4832.png)

Biome size 8:
![2015-10-29_13 22 12](https://cloud.githubusercontent.com/assets/2230216/10828075/67cb3c36-7e40-11e5-8700-e543e7e78de5.png)

Anything over 10 and you're starting to get really large biomes, and it may seem to just be one biome. I'm not saying it isn't actually one biome, but it's a strong possibility that with numbers that high, you just haven't actually left that biome because it's so massive. Or perhaps the size algorithm gets wonky when it's that large. I can't say. The early generation code is a giant clusterfuck of obfuscated variables.

You'll want to keep your sizes under around 10, unless you want insane biomes. Let me know if it still appears to be one biome.

**Comment by Teibidh** [comment]
Fair enough, I will point out though that your documentation says "radius in chunks", a 10 chunk radius would be a 20 chunk diameter, only 320 blocks. What it sounds like, based on what you're saying and the screen shots, is that that number is actually closer to what's used by the biome size thing in vanilla where the "default" is 4 and "large biomes" is 6.

I will give this a whirl using that logic and see what happens. Thanks.

**Comment by superckl** [comment]
I'm not certain that it's actually the radius. That's just a guess based on observed behavior. If you are still having issues, you can continue to comment here, but I'm going to consider this issue resolved for now.

**Comment by Teibidh** [comment]
It does seem to line up with the "usual" biome sizing where 4 is standard
and 6 is  Vanilla's large biomes. Confirmed non-issue, though.
