### ISSUE TITLE
single biome world option?

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#54]
is there any possible way to make a world with proper coded single biome world instead of relying on other mods and manually removing 100+ vanilla/modded biomes?

i know other mods have it but when u have multiple world gens running it causes ALOT of lag generating new biomes. i wanna elimate number of mods on world gen that i can.

that guys dim world edit mod doesnt work and he stopped coding it. so ur mod is literly the last mod that is able to change overworld

**Comment by nanakisan** [comment]
just use the desert world example script. Change the desert = forBiomes(2) string to be whatever biome you want. bam zoom zip zop done

**Comment by superckl** [comment]
Link to said script: https://github.com/superckl/BiomeTweaker/wiki/Example-Scripts#creating-a-desert-world


As for the Dimensional Control mod, you're really baffling me. **I'm on the team developing it. I just finished writing some code for it.** It's perfect for this sort of large scale world tweak. BiomeTweaker is capable of doing it as well, but it's not meant to.

**Comment by resinate** [comment]
cuz i dont want some really adv mod to 1 simple thing that this should do. all it does is put alot of stress on the game for no reason cuz of lazy coding.

**Comment by superckl** [comment]
Lazy coding? We put a lot of time and effort into the mods we make. You've been reporting tons of issues that are either invalid or make no sense. It's a waste of both of our time. I gave you two solutions to this issue. BiomeTweaker can do this for you.

If you're going to insult modders for making something for *you* to use, I ask that you stop reporting issues to me and the BNBGaming forum thread. Otherwise, rethink your attitude and start using proper grammar and standard reporting practice in your issue reports.
