### ISSUE TITLE
Let it snow in all biomes

### ISSUE THREAD

**Issue by tyra314** [superckl/BiomeTweaker#99]
I tried to let it snow in all biomes with this script:

```
allBiomes = forAllBiomes()
allBiomes.set("temperature", -0.2)
allBiomes.set("enableRain", true)
allBiomes.set("enableSnow", true)
```

It sets the values, e.g., output/Jungle.json
```
{
  "ID": 21,
  "Name": "Jungle",
  "Class": "net.minecraft.world.biome.BiomeJungle",
...
  "Temperature": -0.2,
...
  "Enable Rain": true,
  "Enable Snow": true,
...
}
```

But still it's normal rain, even in previously snowy biomes.

**Comment by superckl** [comment]
Not really sure what to tell you. I tried your script and it's snowing everywhere.
![2017-01-07_12 16 41](https://cloud.githubusercontent.com/assets/2230216/21744858/37294e0c-d4d3-11e6-98ed-bf97d6b5011b.png)

Do you have any screenshots, logs, etc.?

**Comment by MCUmbrella** [comment]
@superckl What he said is true because I'm facing the same problem.
Maybe he forgot to say this problem happens on multiplayer game. I tried the same seed and script in singleplayer and multiplayer game. And I noticed where it should snow in local game became rain in the server.
![图片](https://user-images.githubusercontent.com/40854260/104691280-e5365a00-5740-11eb-83cc-2c0e92285b06.png)

**Comment by whirlwindnoa** [comment]
hi i'm experiencing the same issue, it rains but snow appears on the ground "

in multiplayer as well!
